#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-PointGroup-D4
version:      0.01
version_from: D4.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
